import { arbitrumSepolia, baseSepolia, sepolia } from "viem/chains";
import { Coprocessor, Token } from "./types";
import addresses from "./addresses";

export const tokensMap: {
  [chainId: number]: { [symbol: string]: Token };
} = {
  [sepolia.id]: {
    cUSDC: {
      symbol: "cUSDC",
      address: addresses[sepolia.id].cUSDC,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].USDC,
      coprocessor: Coprocessor.ZAMA,
    },
    eUSDC: {
      symbol: "eUSDC",
      address: addresses[sepolia.id].eUSDC,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].USDC,
      coprocessor: Coprocessor.FHENIX,
    },
    cUSDT: {
      symbol: "cUSDT",
      address: addresses[sepolia.id].cUSDT,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].USDT,
      coprocessor: Coprocessor.ZAMA,
    },
    eUSDT: {
      symbol: "eUSDT",
      address: addresses[sepolia.id].eUSDT,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].USDT,
      coprocessor: Coprocessor.FHENIX,
    },
    cDAI: {
      symbol: "cDAI",
      address: addresses[sepolia.id].cDAI,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].DAI,
      coprocessor: Coprocessor.ZAMA,
    },
    eDAI: {
      symbol: "eDAI",
      address: addresses[sepolia.id].eDAI,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].DAI,
      coprocessor: Coprocessor.FHENIX,
    },
    cUNI: {
      symbol: "cUNI",
      address: addresses[sepolia.id].cUNI,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].UNI,
      coprocessor: Coprocessor.ZAMA,
    },
    eUNI: {
      symbol: "eUNI",
      address: addresses[sepolia.id].eUNI,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].UNI,
      coprocessor: Coprocessor.FHENIX,
    },
    cXFL: {
      symbol: "cXFL",
      address: addresses[sepolia.id].cXFL,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].XFL,
      coprocessor: Coprocessor.ZAMA,
    },
    eXFL: {
      symbol: "eXFL",
      address: addresses[sepolia.id].eXFL,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].XFL,
      coprocessor: Coprocessor.FHENIX,
    },
    cAAVE: {
      symbol: "cAAVE",
      address: addresses[sepolia.id].cAAVE,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].AAVE,
      coprocessor: Coprocessor.ZAMA,
    },
    eAAVE: {
      symbol: "eAAVE",
      address: addresses[sepolia.id].eAAVE,
      chainId: sepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[sepolia.id].AAVE,
      coprocessor: Coprocessor.FHENIX,
    },
  },
  [arbitrumSepolia.id]: {
    eUSDC: {
      symbol: "eUSDC",
      address: addresses[arbitrumSepolia.id].eUSDC,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].USDC,
      coprocessor: Coprocessor.FHENIX,
    },
    eUSDT: {
      symbol: "eUSDT",
      address: addresses[arbitrumSepolia.id].eUSDT,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].USDT,
      coprocessor: Coprocessor.FHENIX,
    },
    eDAI: {
      symbol: "eDAI",
      address: addresses[arbitrumSepolia.id].eDAI,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].DAI,
      coprocessor: Coprocessor.FHENIX,
    },
    eUNI: {
      symbol: "eUNI",
      address: addresses[arbitrumSepolia.id].eUNI,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].UNI,
      coprocessor: Coprocessor.FHENIX,
    },
    eU: {
      symbol: "eU",
      address: addresses[arbitrumSepolia.id].eU,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].U,
      coprocessor: Coprocessor.FHENIX,
    },
    eXFL: {
      symbol: "eXFL",
      address: addresses[arbitrumSepolia.id].eXFL,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].XFL,
      coprocessor: Coprocessor.FHENIX,
    },
    eAAVE: {
      symbol: "eAAVE",
      address: addresses[arbitrumSepolia.id].eAAVE,
      chainId: arbitrumSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[arbitrumSepolia.id].AAVE,
      coprocessor: Coprocessor.FHENIX,
    },
  },
  [baseSepolia.id]: {
    eUSDC: {
      symbol: "eUSDC",
      address: addresses[baseSepolia.id].eUSDC,
      chainId: baseSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[baseSepolia.id].USDC,
      coprocessor: Coprocessor.FHENIX,
    },
    eUSDT: {
      symbol: "eUSDT",
      address: addresses[baseSepolia.id].eUSDT,
      chainId: baseSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[baseSepolia.id].USDT,
      coprocessor: Coprocessor.FHENIX,
    },
    eDAI: {
      symbol: "eDAI",
      address: addresses[baseSepolia.id].eDAI,
      chainId: baseSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[baseSepolia.id].DAI,
      coprocessor: Coprocessor.FHENIX,
    },
    eUNI: {
      symbol: "eUNI",
      address: addresses[baseSepolia.id].eUNI,
      chainId: baseSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[baseSepolia.id].UNI,
      coprocessor: Coprocessor.FHENIX,
    },
    eXFL: {
      symbol: "eXFL",
      address: addresses[baseSepolia.id].eXFL,
      chainId: baseSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[baseSepolia.id].XFL,
      coprocessor: Coprocessor.FHENIX,
    },
    eAAVE: {
      symbol: "eAAVE",
      address: addresses[baseSepolia.id].eAAVE,
      chainId: baseSepolia.id,
      decimals: 6,
      isConfidential: true,
      underlyingTokenAddress: addresses[baseSepolia.id].AAVE,
      coprocessor: Coprocessor.FHENIX,
    },
  },
};

const tokens: { [chainId: number]: Token[] } = Object.entries(tokensMap).reduce(
  (acc: { [chainId: number]: Token[] }, [chainId, tokens]) => {
    acc[+chainId] = Object.values(tokens);
    return acc;
  },
  {}
);

export default tokens;
